// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using Microsoft.VisualBasic;

namespace GrblPanel.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("GrblPanel.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to For more details on this app, please visit: .
        /// </summary>
        internal static string AboutBox_AboutBox_Load_ForMoreDetailsOnThisAppPleaseVisit
        {
            get
            {
                return ResourceManager.GetString("AboutBox_AboutBox_Load_ForMoreDetailsOnThisAppPleaseVisit", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to GrblPanel is designed for use with Grbl 0.9G or later..
        /// </summary>
        internal static string AboutBox_AboutBox_Load_GrblPanelIsDesignedForUseWithGrbl09GOrLater
        {
            get
            {
                return ResourceManager.GetString("AboutBox_AboutBox_Load_GrblPanelIsDesignedForUseWithGrbl09GOrLater", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Button_Connection_Text_Connect
        {
            get
            {
                return ResourceManager.GetString("Button_Connection_Text_Connect", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Alarm lock .
        /// </summary>
        internal static string GrblGcodeView_AlarmLock
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_AlarmLock", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Arc radius error .
        /// </summary>
        internal static string GrblGcodeView_ArcRadiusError
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_ArcRadiusError", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Axis command conflict .
        /// </summary>
        internal static string GrblGcodeView_AxisCommandConflict
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_AxisCommandConflict", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Axis words exist .
        /// </summary>
        internal static string GrblGcodeView_AxisWordsExist
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_AxisWordsExist", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Bad number format .
        /// </summary>
        internal static string GrblGcodeView_BadNumberFormat
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_BadNumberFormat", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Build info length .
        /// </summary>
        internal static string GrblGcodeView_BuildInfoLength
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_BuildInfoLength", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Check door .
        /// </summary>
        internal static string GrblGcodeView_CheckDoor
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_CheckDoor", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Command value is not integer .
        /// </summary>
        internal static string GrblGcodeView_CommandValueIsNotInteger
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_CommandValueIsNotInteger", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to EEPROM read fail, using Defaults .
        /// </summary>
        internal static string GrblGcodeView_EEPROMReadFailUsingDefaults
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_EEPROMReadFailUsingDefaults", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Expected command letter .
        /// </summary>
        internal static string GrblGcodeView_ExpectedCommandLetter
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_ExpectedCommandLetter", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to G43 dynamic axis error .
        /// </summary>
        internal static string GrblGcodeView_G43DynamicAxisError
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_G43DynamicAxisError", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to G53 invalid motion mode .
        /// </summary>
        internal static string GrblGcodeView_G53InvalidMotionMode
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_G53InvalidMotionMode", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Homing is not enabled .
        /// </summary>
        internal static string GrblGcodeView_HomingIsNotEnabled
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_HomingIsNotEnabled", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Invalid line number .
        /// </summary>
        internal static string GrblGcodeView_InvalidLineNumber
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_InvalidLineNumber", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Invalid statement .
        /// </summary>
        internal static string GrblGcodeView_InvalidStatement
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_InvalidStatement", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Invalid target .
        /// </summary>
        internal static string GrblGcodeView_InvalidTarget
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_InvalidTarget", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Tool number &gt;max supported.
        /// </summary>
        internal static string GrblGcodeView_InvalidToolNumber
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_InvalidToolNumber", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Jog format .
        /// </summary>
        internal static string GrblGcodeView_JogFormat
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_JogFormat", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Jog Travel .
        /// </summary>
        internal static string GrblGcodeView_JogTravel
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_JogTravel", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Line overflow .
        /// </summary>
        internal static string GrblGcodeView_LineOverflow
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_LineOverflow", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Modal group violation .
        /// </summary>
        internal static string GrblGcodeView_ModalGroupViolation
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_ModalGroupViolation", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Line.
        /// </summary>
        internal static string GrblGcodeView_New_Line
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_New_Line", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to No axis words .
        /// </summary>
        internal static string GrblGcodeView_NoAxisWords
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_NoAxisWords", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to No axis words in plane .
        /// </summary>
        internal static string GrblGcodeView_NoAxisWordsInPlane
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_NoAxisWordsInPlane", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to No offsets in plane .
        /// </summary>
        internal static string GrblGcodeView_NoOffsetsInPlane
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_NoOffsetsInPlane", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Not idle .
        /// </summary>
        internal static string GrblGcodeView_NotIdle
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_NotIdle", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Setting disabled .
        /// </summary>
        internal static string GrblGcodeView_SettingDisabled
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_SettingDisabled", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Step rate &gt; 30kHz .
        /// </summary>
        internal static string GrblGcodeView_StepRate30kHz
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_StepRate30kHz", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Undefined feed rate .
        /// </summary>
        internal static string GrblGcodeView_UndefinedFeedRate
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_UndefinedFeedRate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Unsupported command .
        /// </summary>
        internal static string GrblGcodeView_UnsupportedCommand
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_UnsupportedCommand", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Unsupported coordinate system .
        /// </summary>
        internal static string GrblGcodeView_UnsupportedCoordinateSystem
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_UnsupportedCoordinateSystem", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Unused words .
        /// </summary>
        internal static string GrblGcodeView_UnusedWords
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_UnusedWords", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Value &lt; 0 .
        /// </summary>
        internal static string GrblGcodeView_Value0
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_Value0", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Value &lt; 3 usec .
        /// </summary>
        internal static string GrblGcodeView_Value3Usec
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_Value3Usec", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Value word missing .
        /// </summary>
        internal static string GrblGcodeView_ValueWordMissing
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_ValueWordMissing", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Word repeated .
        /// </summary>
        internal static string GrblGcodeView_WordRepeated
        {
            get
            {
                return ResourceManager.GetString("GrblGcodeView_WordRepeated", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Data Validation Error.
        /// </summary>
        internal static string GrblGui_btnAdd_Click_DataValidationError
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnAdd_Click_DataValidationError", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to You cannot create a macro without a name..
        /// </summary>
        internal static string GrblGui_btnAdd_Click_YouCannotCreateAMacroWithoutAName
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnAdd_Click_YouCannotCreateAMacroWithoutAName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to You need to add some G-code to save a macro.
        /// </summary>
        internal static string GrblGui_btnAdd_Click_YouNeedToAddSomeGCodeToSaveAMacro
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnAdd_Click_YouNeedToAddSomeGCodeToSaveAMacro", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to And A Port Number In The Format.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_And_A_Port_Number_In_The_Format
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_And_A_Port_Number_In_The_Format", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to and a port number in the format.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_AndAPortNumberInTheFormat
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_AndAPortNumberInTheFormat", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Connect.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Connect
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Connect", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Connect Error.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Connect_Error
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Connect_Error", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Disconnect
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Disconnect", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Disconnected
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Disconnected", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to End.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_End
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_End", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Idle.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Idle
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Idle", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Or Connect The Cable.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Or_Connect_The_Cable
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Or_Connect_The_Cable", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to or connect the cable.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_OrConnectTheCable
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_OrConnectTheCable", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Please Enter An IP Address.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Please_Enter_An_IP_Address
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Please_Enter_An_IP_Address", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Please Select A Com Port.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_Please_Select_A_Com_Port
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Please_Select_A_Com_Port", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Please enter an IP Address.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_PleaseEnterAnIPAddress
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_PleaseEnterAnIPAddress", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Please select a Com port.
        /// </summary>
        internal static string GrblGui_btnConnDisconnect_Click_PleaseSelectAComPort
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_PleaseSelectAComPort", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Are you sure you want to delete the .
        /// </summary>
        internal static string GrblGui_btnDeleteMacro_Click_AreYouSureYouWantToDeleteThe
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnDeleteMacro_Click_AreYouSureYouWantToDeleteThe", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string GrblGui_btnDeleteMacro_Click_ConfirmDelete
        {
            get
            {
                return ResourceManager.GetString("GrblGui_btnDeleteMacro_Click_ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Update.
        /// </summary>
        internal static string GrblGui_dgMacros_DoubleClick_Update
        {
            get
            {
                return ResourceManager.GetString("GrblGui_dgMacros_DoubleClick_Update", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Are You Certain That You Want To Close.
        /// </summary>
        internal static string GrblGui_grblgui_unload_Are_You_Certain_That_You_Want_To_Close
        {
            get
            {
                return ResourceManager.GetString("GrblGui_grblgui_unload_Are_You_Certain_That_You_Want_To_Close", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Are you certain that you want to close?.
        /// </summary>
        internal static string GrblGui_grblgui_unload_AreYouCertainThatYouWantToClose
        {
            get
            {
                return ResourceManager.GetString("GrblGui_grblgui_unload_AreYouCertainThatYouWantToClose", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Are you sure you want to exit without saving your Macro changes?.
        /// </summary>
        internal static string GrblGui_GrblMacroButtons_FormClosing_AreYouSureYouWantToExitWithoutSavingYourMacroChanges
        {
            get
            {
                return ResourceManager.GetString("GrblGui_GrblMacroButtons_FormClosing_AreYouSureYouWantToExitWithoutSavingYourMacr" + "oChanges", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Confirm exit without saving..
        /// </summary>
        internal static string GrblGui_GrblMacroButtons_FormClosing_ConfirmExitWithoutSaving
        {
            get
            {
                return ResourceManager.GetString("GrblGui_GrblMacroButtons_FormClosing_ConfirmExitWithoutSaving", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Add.
        /// </summary>
        internal static string GrblGui_GrblMacroButtons_Load_Add
        {
            get
            {
                return ResourceManager.GetString("GrblGui_GrblMacroButtons_Load_Add", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to CHECK.
        /// </summary>
        internal static string GrblGui_showGrblStatus_CHECK
        {
            get
            {
                return ResourceManager.GetString("GrblGui_showGrblStatus_CHECK", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to HOLD.
        /// </summary>
        internal static string GrblGui_showGrblStatus_HOLD
        {
            get
            {
                return ResourceManager.GetString("GrblGui_showGrblStatus_HOLD", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to IDLE.
        /// </summary>
        internal static string GrblGui_showGrblStatus_IDLE
        {
            get
            {
                return ResourceManager.GetString("GrblGui_showGrblStatus_IDLE", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Resume.
        /// </summary>
        internal static string GrblGui_showGrblStatus_Resume
        {
            get
            {
                return ResourceManager.GetString("GrblGui_showGrblStatus_Resume", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to RUN.
        /// </summary>
        internal static string GrblGui_showGrblStatus_RUN
        {
            get
            {
                return ResourceManager.GetString("GrblGui_showGrblStatus_RUN", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Commit all changes to Settings and close.
        /// </summary>
        internal static string GrblGui_UpdateToolTip_CommitAllChangesToSettingsAndClose
        {
            get
            {
                return ResourceManager.GetString("GrblGui_UpdateToolTip_CommitAllChangesToSettingsAndClose", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to DblClick name to edit macro.
        /// </summary>
        internal static string GrblGui_UpdateToolTip_DblClickNameToEditMacro
        {
            get
            {
                return ResourceManager.GetString("GrblGui_UpdateToolTip_DblClickNameToEditMacro", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Delete the selected macro.
        /// </summary>
        internal static string GrblGui_UpdateToolTip_DeleteTheSelectedMacro
        {
            get
            {
                return ResourceManager.GetString("GrblGui_UpdateToolTip_DeleteTheSelectedMacro", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to G-Code to send when the button is clicked..
        /// </summary>
        internal static string GrblGui_UpdateToolTip_GCodeToSendWhenTheButtonIsClicked
        {
            get
            {
                return ResourceManager.GetString("GrblGui_UpdateToolTip_GCodeToSendWhenTheButtonIsClicked", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Get me outta here, cancel all changes.
        /// </summary>
        internal static string GrblGui_UpdateToolTip_GetMeOuttaHereCancelAllChanges
        {
            get
            {
                return ResourceManager.GetString("GrblGui_UpdateToolTip_GetMeOuttaHereCancelAllChanges", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Limit is 5 macros.
        /// </summary>
        internal static string GrblGui_UpdateToolTip_LimitIs5Macros
        {
            get
            {
                return ResourceManager.GetString("GrblGui_UpdateToolTip_LimitIs5Macros", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Name appears on the button, so keep it small.
        /// </summary>
        internal static string GrblGui_UpdateToolTip_NameAppearsOnTheButtonSoKeepItSmall
        {
            get
            {
                return ResourceManager.GetString("GrblGui_UpdateToolTip_NameAppearsOnTheButtonSoKeepItSmall", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Error on close of Grbl port.
        /// </summary>
        internal static string GrblIF_Disconnect_ErrorOnCloseOfGrblPort
        {
            get
            {
                return ResourceManager.GetString("GrblIF_Disconnect_ErrorOnCloseOfGrblPort", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Fatal error on write to Grbl.
        /// </summary>
        internal static string GrblIF_sendData_FatalErrorOnWriteToGrbl
        {
            get
            {
                return ResourceManager.GetString("GrblIF_sendData_FatalErrorOnWriteToGrbl", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to a accel, mm/sec^2.
        /// </summary>
        internal static string GrblSettings_AAccelMmSec2
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_AAccelMmSec2", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  a max rate, mm/min.
        /// </summary>
        internal static string GrblSettings_AMaxRateMmMin
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_AMaxRateMmMin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to a max travel, mm.
        /// </summary>
        internal static string GrblSettings_AMaxTravelMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_AMaxTravelMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to arc tolerance, mm.
        /// </summary>
        internal static string GrblSettings_ArcToleranceMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_ArcToleranceMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to a, step/mm.
        /// </summary>
        internal static string GrblSettings_AStepMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_AStepMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to dir port invert mask:.
        /// </summary>
        internal static string GrblSettings_DirPortInvertMask
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_DirPortInvertMask", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Value.
        /// </summary>
        internal static string GrblSettings_FillSettings_Value
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_FillSettings_Value", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to hard limits, bool.
        /// </summary>
        internal static string GrblSettings_HardLimitsBool
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_HardLimitsBool", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to homing cycle, bool.
        /// </summary>
        internal static string GrblSettings_HomingCycleBool
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_HomingCycleBool", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  homing debounce, msec.
        /// </summary>
        internal static string GrblSettings_HomingDebounceMsec
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_HomingDebounceMsec", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to homing dir invert mask.
        /// </summary>
        internal static string GrblSettings_HomingDirInvertMask
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_HomingDirInvertMask", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  homing feed, mm/min.
        /// </summary>
        internal static string GrblSettings_HomingFeedMmMin
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_HomingFeedMmMin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to homing pull-off, mm.
        /// </summary>
        internal static string GrblSettings_HomingPullOffMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_HomingPullOffMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to homing seek, mm/min.
        /// </summary>
        internal static string GrblSettings_HomingSeekMmMin
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_HomingSeekMmMin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to junction deviation, mm.
        /// </summary>
        internal static string GrblSettings_JunctionDeviationMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_JunctionDeviationMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to laser mode.
        /// </summary>
        internal static string GrblSettings_LaserMode
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_LaserMode", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  limit pins invert, bool.
        /// </summary>
        internal static string GrblSettings_LimitPinsInvertBool
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_LimitPinsInvertBool", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to probe pin invert, bool.
        /// </summary>
        internal static string GrblSettings_ProbePinInvertBool
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_ProbePinInvertBool", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to report inches, bool.
        /// </summary>
        internal static string GrblSettings_ReportInchesBool
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_ReportInchesBool", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to rpm max.
        /// </summary>
        internal static string GrblSettings_RpmMax
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_RpmMax", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to rpm min.
        /// </summary>
        internal static string GrblSettings_RpmMin
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_RpmMin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to soft limits, bool.
        /// </summary>
        internal static string GrblSettings_SoftLimitsBool
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_SoftLimitsBool", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to status report mask.
        /// </summary>
        internal static string GrblSettings_StatusReportMask
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_StatusReportMask", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  step enable invert, bool.
        /// </summary>
        internal static string GrblSettings_StepEnableInvertBool
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_StepEnableInvertBool", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to step idle delay, msec.
        /// </summary>
        internal static string GrblSettings_StepIdleDelayMsec
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_StepIdleDelayMsec", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to step port invert mask:.
        /// </summary>
        internal static string GrblSettings_StepPortInvertMask
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_StepPortInvertMask", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to step pulse, usec.
        /// </summary>
        internal static string GrblSettings_StepPulseUsec
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_StepPulseUsec", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to x accel, mm/sec^2.
        /// </summary>
        internal static string GrblSettings_XAccelMmSec2
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_XAccelMmSec2", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to x max rate, mm/min.
        /// </summary>
        internal static string GrblSettings_XMaxRateMmMin
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_XMaxRateMmMin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to x max travel, mm.
        /// </summary>
        internal static string GrblSettings_XMaxTravelMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_XMaxTravelMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to x, step/mm.
        /// </summary>
        internal static string GrblSettings_XStepMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_XStepMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to y accel, mm/sec^2.
        /// </summary>
        internal static string GrblSettings_YAccelMmSec2
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_YAccelMmSec2", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to y max rate, mm/min.
        /// </summary>
        internal static string GrblSettings_YMaxRateMmMin
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_YMaxRateMmMin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to y max travel, mm.
        /// </summary>
        internal static string GrblSettings_YMaxTravelMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_YMaxTravelMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to y, step/mm.
        /// </summary>
        internal static string GrblSettings_YStepMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_YStepMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to z accel, mm/sec^2.
        /// </summary>
        internal static string GrblSettings_ZAccelMmSec2
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_ZAccelMmSec2", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to z max rate, mm/min.
        /// </summary>
        internal static string GrblSettings_ZMaxRateMmMin
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_ZMaxRateMmMin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to z max travel, mm.
        /// </summary>
        internal static string GrblSettings_ZMaxTravelMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_ZMaxTravelMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to z, step/mm.
        /// </summary>
        internal static string GrblSettings_ZStepMm
        {
            get
            {
                return ResourceManager.GetString("GrblSettings_ZStepMm", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Start.
        /// </summary>
        internal static string MsgFilter_PreFilterMessage_Start
        {
            get
            {
                return ResourceManager.GetString("MsgFilter_PreFilterMessage_Start", resourceCulture);
            }
        }
    }
}