// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;

namespace GrblPanel.My
{
    [CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
    {
        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        #region My.Settings Auto-Save Functionality
        /* TODO ERROR: Skipped IfDirectiveTrivia
        #If _MyType = "WindowsForms" Then
        */
        private static bool addedHandler;
        private static object addedHandlerLockObject = new object();

        [DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private static void AutoSaveSettings(object sender, EventArgs e)
        {
            if (MyProject.Application.SaveMySettingsOnExit)
            {
                MySettingsProperty.Settings.Save();
            }
        }
        /* TODO ERROR: Skipped EndIfDirectiveTrivia
        #End If
        */
        #endregion

        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia
                #If _MyType = "WindowsForms" Then
                */
                if (!addedHandler)
                {
                    lock (addedHandlerLockObject)
                    {
                        if (!addedHandler)
                        {
                            MyProject.Application.Shutdown += AutoSaveSettings;
                            addedHandler = true;
                        }
                    }
                }
                /* TODO ERROR: Skipped EndIfDirectiveTrivia
                #End If
                */
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Port
        {
            get
            {
                return Conversions.ToString(this["Port"]);
            }

            set
            {
                this["Port"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("115200")]
        public string Baud
        {
            get
            {
                return Conversions.ToString(this["Baud"]);
            }

            set
            {
                this["Baud"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool JoggingUnitsMetric
        {
            get
            {
                return Conversions.ToBoolean(this["JoggingUnitsMetric"]);
            }

            set
            {
                this["JoggingUnitsMetric"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("G90 G10 L20 P0 X0 Y0 Z0")]
        public string Work0Cmd
        {
            get
            {
                return Conversions.ToString(this["Work0Cmd"]);
            }

            set
            {
                this["Work0Cmd"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool StatusPollEnabled
        {
            get
            {
                return Conversions.ToBoolean(this["StatusPollEnabled"]);
            }

            set
            {
                this["StatusPollEnabled"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool StatusVerbose
        {
            get
            {
                return Conversions.ToBoolean(this["StatusVerbose"]);
            }

            set
            {
                this["StatusVerbose"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("200")]
        public string StatusPollInterval
        {
            get
            {
                return Conversions.ToString(this["StatusPollInterval"]);
            }

            set
            {
                this["StatusPollInterval"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("G90 G10 L20 P0 X0")]
        public string WorkX0Cmd
        {
            get
            {
                return Conversions.ToString(this["WorkX0Cmd"]);
            }

            set
            {
                this["WorkX0Cmd"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("G90 G10 L20 P0 Y0")]
        public string WorkY0Cmd
        {
            get
            {
                return Conversions.ToString(this["WorkY0Cmd"]);
            }

            set
            {
                this["WorkY0Cmd"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("G90 G10 L20 P0 Z0")]
        public string WorkZ0Cmd
        {
            get
            {
                return Conversions.ToString(this["WorkZ0Cmd"]);
            }

            set
            {
                this["WorkZ0Cmd"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("100,50,10,5")]
        public string JoggingFRImperial
        {
            get
            {
                return Conversions.ToString(this["JoggingFRImperial"]);
            }

            set
            {
                this["JoggingFRImperial"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1,0.1,0.01,0.001")]
        public string JoggingFIImperial
        {
            get
            {
                return Conversions.ToString(this["JoggingFIImperial"]);
            }

            set
            {
                this["JoggingFIImperial"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("10,1,0.1,0.01 ")]
        public string JoggingFIMEtric
        {
            get
            {
                return Conversions.ToString(this["JoggingFIMEtric"]);
            }

            set
            {
                this["JoggingFIMEtric"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1000,500,100,5")]
        public string JoggingFRMetric
        {
            get
            {
                return Conversions.ToString(this["JoggingFRMetric"]);
            }

            set
            {
                this["JoggingFRMetric"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("17")]
        public string QBuffMaxSize
        {
            get
            {
                return Conversions.ToString(this["QBuffMaxSize"]);
            }

            set
            {
                this["QBuffMaxSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("127")]
        public string RBuffMaxSize
        {
            get
            {
                return Conversions.ToString(this["RBuffMaxSize"]);
            }

            set
            {
                this["RBuffMaxSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("2.5")]
        public string JoggingXRepeat
        {
            get
            {
                return Conversions.ToString(this["JoggingXRepeat"]);
            }

            set
            {
                this["JoggingXRepeat"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("2.5")]
        public string JoggingZRepeat
        {
            get
            {
                return Conversions.ToString(this["JoggingZRepeat"]);
            }

            set
            {
                this["JoggingZRepeat"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("2.5")]
        public string JoggingYRepeat
        {
            get
            {
                return Conversions.ToString(this["JoggingYRepeat"]);
            }

            set
            {
                this["JoggingYRepeat"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool GCodePauseOnError
        {
            get
            {
                return Conversions.ToBoolean(this["GCodePauseOnError"]);
            }

            set
            {
                this["GCodePauseOnError"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool GrblConnectOnLoad
        {
            get
            {
                return Conversions.ToBoolean(this["GrblConnectOnLoad"]);
            }

            set
            {
                this["GrblConnectOnLoad"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool JoggingUseKeyboard
        {
            get
            {
                return Conversions.ToBoolean(this["JoggingUseKeyboard"]);
            }

            set
            {
                this["JoggingUseKeyboard"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool LeftHandedGUI
        {
            get
            {
                return Conversions.ToBoolean(this["LeftHandedGUI"]);
            }

            set
            {
                this["LeftHandedGUI"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("G28")]
        public string MachineSpclPosition1
        {
            get
            {
                return Conversions.ToString(this["MachineSpclPosition1"]);
            }

            set
            {
                this["MachineSpclPosition1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("G30")]
        public string MachineSpclPosition2
        {
            get
            {
                return Conversions.ToString(this["MachineSpclPosition2"]);
            }

            set
            {
                this["MachineSpclPosition2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("$132")]
        public string GrblLastParamID
        {
            get
            {
                return Conversions.ToString(this["GrblLastParamID"]);
            }

            set
            {
                this["GrblLastParamID"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("I2")]
        public string JoggingFIDefault
        {
            get
            {
                return Conversions.ToString(this["JoggingFIDefault"]);
            }

            set
            {
                this["JoggingFIDefault"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("F2")]
        public string JoggingFRDefault
        {
            get
            {
                return Conversions.ToString(this["JoggingFRDefault"]);
            }

            set
            {
                this["JoggingFRDefault"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("txt")]
        public string DefaultFileExt
        {
            get
            {
                return Conversions.ToString(this["DefaultFileExt"]);
            }

            set
            {
                this["DefaultFileExt"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string IPAddress
        {
            get
            {
                return Conversions.ToString(this["IPAddress"]);
            }

            set
            {
                this["IPAddress"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string ConnectionType
        {
            get
            {
                return Conversions.ToString(this["ConnectionType"]);
            }

            set
            {
                this["ConnectionType"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Macro1
        {
            get
            {
                return Conversions.ToString(this["Macro1"]);
            }

            set
            {
                this["Macro1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Macro2
        {
            get
            {
                return Conversions.ToString(this["Macro2"]);
            }

            set
            {
                this["Macro2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Macro3
        {
            get
            {
                return Conversions.ToString(this["Macro3"]);
            }

            set
            {
                this["Macro3"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Macro4
        {
            get
            {
                return Conversions.ToString(this["Macro4"]);
            }

            set
            {
                this["Macro4"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Macro5
        {
            get
            {
                return Conversions.ToString(this["Macro5"]);
            }

            set
            {
                this["Macro5"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool UpgradeSettings
        {
            get
            {
                return Conversions.ToBoolean(this["UpgradeSettings"]);
            }

            set
            {
                this["UpgradeSettings"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string TruncationDigits
        {
            get
            {
                return Conversions.ToString(this["TruncationDigits"]);
            }

            set
            {
                this["TruncationDigits"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1.5")]
        public string StartDelay
        {
            get
            {
                return Conversions.ToString(this["StartDelay"]);
            }

            set
            {
                this["StartDelay"] = value;
            }
        }
    }
}

namespace GrblPanel.My
{
    [HideModuleName()]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal static class MySettingsProperty
    {
        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}